-- ============================================================
-- RETAIL/E-COMMERCE DATA WAREHOUSE - SNOWFLAKE SCHEMA DESIGN
-- ============================================================

-- 1. CREATE DATABASE AND SCHEMAS
CREATE DATABASE IF NOT EXISTS NORMALIZE_DW;

USE DATABASE NORMALIZE_DW;

CREATE SCHEMA IF NOT EXISTS STAGING; 
CREATE SCHEMA IF NOT EXISTS DIMENSIONS;
CREATE SCHEMA IF NOT EXISTS FACTS;