-- ============================================================
-- RETAIL/E-COMMERCE DATA WAREHOUSE - SNOWFLAKE SCHEMA DESIGN
-- ============================================================

-- 1. CREATE DATABASE AND SCHEMAS
CREATE OR REPLACE DATABASE NORMALIZE_DW;

USE DATABASE NORMALIZE_DW;

CREATE OR REPLACE SCHEMA STAGING; 
CREATE OR REPLACE SCHEMA DIMENSIONS;
CREATE OR REPLACE SCHEMA FACTS;