LIST @AIRLINE_STAGE ; 

SELECT 
*
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'AIRLINE_SOURCE'
ORDER BY TABLE_NAME; 

SELECT * FROM AIRCRAFT LIMIT 10 ;
SELECT * FROM AIRCRAFT_MAINTENANCE_HISTORY LIMIT 10 ;
SELECT * FROM AIRCRAFT_MODELS LIMIT 10 ;
SELECT * FROM AIRLINES LIMIT 10 ;
SELECT * FROM AIRPORTS LIMIT 10 ;
SELECT * FROM ANCILLARY_SERVICES LIMIT 10 ;
SELECT * FROM BAGGAGE LIMIT 10 ;
SELECT * FROM BOARDING_PASSES LIMIT 10 ;
SELECT * FROM BOOKINGS LIMIT 10 ;
SELECT * FROM CHECK_IN_EVENTS LIMIT 10 ;
SELECT * FROM CREW_ASSIGNMENTS LIMIT 10 ;
SELECT * FROM CREW_MEMBERS LIMIT 10 ;
SELECT * FROM CUSTOMERS LIMIT 10 ;
SELECT * FROM CUSTOMER_SUPPORT_TICKETS LIMIT 10 ;
SELECT * FROM FEEDBACK LIMIT 10 ;
SELECT * FROM FLIGHTS LIMIT 10 ;
SELECT * FROM FLIGHT_CANCELLATIONS LIMIT 10 ;
SELECT * FROM FLIGHT_DELAYS LIMIT 10 ;
SELECT * FROM FLIGHT_ROUTES LIMIT 10 ;
SELECT * FROM FLIGHT_SCHEDULES LIMIT 10 ;
SELECT * FROM FLIGHT_STATUS_LOGS LIMIT 10 ;
SELECT * FROM FUEL_USAGE LIMIT 10 ;
SELECT * FROM GATE_INFORMATION LIMIT 10 ;
SELECT * FROM LOYALTY_MEMBERS LIMIT 10 ;
SELECT * FROM LOYALTY_TRANSACTIONS LIMIT 10 ;
SELECT * FROM MAINTENANCE_LOGS LIMIT 10 ;
SELECT * FROM PASSENGERS LIMIT 10 ;
SELECT * FROM PAYMENTS LIMIT 10 ;
SELECT * FROM REFUNDS LIMIT 10 ;
SELECT * FROM SEAT_ASSIGNMENTS LIMIT 10 ;
SELECT * FROM TICKETS LIMIT 10 ;
SELECT * FROM WEATHER_CONDITIONS LIMIT 10 ;