USE DATABASE RITSKYSNOW ; 
USE SCHEMA AIRLINE_SOURCE ;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE() ;
CREATE STAGE AIRLINE_STAGE ;
SHOW STAGES ;
DESC STAGE AIRLINE_STAGE ; 

PUT 'file:///home/ritik/Snowflake-Data-Engineering-Project/Full-Load-ELT-Data-Warehouse/extract_data/airline_reservation_dataset/data/*.csv'
@AIRLINE_STAGE
AUTO_COMPRESS = TRUE ;

LIST @AIRLINE_STAGE ; 

SELECT
    $1,
    $2,
    $3,
    $4
FROM @AIRLINE_STAGE/aircraft.csv.gz
LIMIT 10;

SELECT 
    TABLE_NAME,
    TABLE_OWNER,
    TABLE_TYPE,
    LAST_DDL_BY,
    COMMENT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'AIRLINE_SOURCE'
ORDER BY TABLE_NAME ;

SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    DATA_TYPE_ALIAS,
KIND
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'AIRLINE_SOURCE' ;




--=================================================================================================
--=================================================================================================
--=================================================================================================

COPY INTO AIRCRAFT
FROM @AIRLINE_STAGE/aircraft.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO AIRCRAFT_MAINTENANCE_HISTORY
FROM @AIRLINE_STAGE/aircraft_maintenance_history.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO AIRCRAFT_MODELS
FROM @AIRLINE_STAGE/aircraft_models.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO AIRLINES
FROM @AIRLINE_STAGE/airlines.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO AIRPORTS
FROM @AIRLINE_STAGE/airports.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO ANCILLARY_SERVICES
FROM @AIRLINE_STAGE/ancillary_services.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO BAGGAGE
FROM @AIRLINE_STAGE/baggage.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO BOARDING_PASSES
FROM @AIRLINE_STAGE/boarding_passes.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO BOOKINGS
FROM @AIRLINE_STAGE/bookings.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO CHECK_IN_EVENTS
FROM @AIRLINE_STAGE/check_in_events.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO CREW_ASSIGNMENTS
FROM @AIRLINE_STAGE/crew_assignments.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO CREW_MEMBERS
FROM @AIRLINE_STAGE/crew_members.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO CUSTOMERS
FROM @AIRLINE_STAGE/customers.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO CUSTOMER_SUPPORT_TICKETS
FROM @AIRLINE_STAGE/customer_support_tickets.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FEEDBACK
FROM @AIRLINE_STAGE/feedback.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FLIGHTS
FROM @AIRLINE_STAGE/flights.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FLIGHT_CANCELLATIONS
FROM @AIRLINE_STAGE/flight_cancellations.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FLIGHT_DELAYS
FROM @AIRLINE_STAGE/flight_delays.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FLIGHT_ROUTES
FROM @AIRLINE_STAGE/flight_routes.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FLIGHT_SCHEDULES
FROM @AIRLINE_STAGE/flight_schedules.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FLIGHT_STATUS_LOGS
FROM @AIRLINE_STAGE/flight_status_logs.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO FUEL_USAGE
FROM @AIRLINE_STAGE/fuel_usage.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO GATE_INFORMATION
FROM @AIRLINE_STAGE/gate_information.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO LOYALTY_MEMBERS
FROM @AIRLINE_STAGE/loyalty_members.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO LOYALTY_TRANSACTIONS
FROM @AIRLINE_STAGE/loyalty_transactions.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO MAINTENANCE_LOGS
FROM @AIRLINE_STAGE/maintenance_logs.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO PASSENGERS
FROM @AIRLINE_STAGE/passengers.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO PAYMENTS
FROM @AIRLINE_STAGE/payments.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO REFUNDS
FROM @AIRLINE_STAGE/refunds.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO SEAT_ASSIGNMENTS
FROM @AIRLINE_STAGE/seat_assignments.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO TICKETS
FROM @AIRLINE_STAGE/tickets.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;


COPY INTO WEATHER_CONDITIONS
FROM @AIRLINE_STAGE/weather_conditions.csv.gz
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
ON_ERROR = 'ABORT_STATEMENT'
;

--=================================================================================================
--=================================================================================================
--=================================================================================================