USE DATABASE NORMALIZE_DW ;
USE SCHEMA STAGING ; 
SELECT 
    PRODUCT_IDS,
    PRODUCT_NAMES, 
    QUANTITIES, 
    UNIT_PRICES
FROM orders LIMIT 10 ; 

DESCRIBE TABLE orders ;

SELECT 
    *
FROM orders 
WHERE REGEXP_LIKE(PRODUCT_IDS  , '.*[!,|_:;].*')
  AND REGEXP_LIKE(PRODUCT_NAMES, '.*[!,|_:;].*') 
  AND REGEXP_LIKE(QUANTITIES   , '.*[!,|_:;].*') 
  AND REGEXP_LIKE(UNIT_PRICES  , '.*[!,|_:;].*')
LIMIT 10 ;



SELECT * FROM customers LIMIT 10 ; 

SELECT * FROM INFORMATION_SCHEMA.SCHEMATA ;


CREATE TABLE orders_if AS 
    SELECT 
    PRODUCT_IDS,
    PRODUCT_NAMES, 
    QUANTITIES, 
    UNIT_PRICES
FROM orders ;


SELECT * FROM orders_if ;


SELECT
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'STAGING' 
AND TABLE_NAME = 'ORDERS_IF';

